name: Send ROM Release to Telegram
on:
  workflow_dispatch:

jobs:
  post_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Telegram Rich Message
        shell: bash
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          set -euo pipefail

          HTML=$(cat <<EOF
          <a href="https://i.ibb.co/ZRkKV76G/banner.png">&#8203;</a>#duchamp #port #tengeos #a17 #fenrir
          <h1>TengeOS 4.0.0.6.XPSEUXM | Fenrir / Non-Fenrir | Android 17</h1>
          <table bordered>
            <tr>
              <th colspan="2" align="center">Device</th>
            </tr>
            <tr>
              <td>Model</td><td>POCO X6 Pro / REDMI K70E</td>
            </tr>
            <tr>
              <td>Codename</td><td>Duchamp</td>
            </tr>
          </table>
          Released: 25/09/2026<br>
          Maintainer: @wectazz
          <details>
            <summary><code>About ROM</code></summary>
            <table bordered>
              <tr>
                <th colspan="2" align="center">Build information</th>
              </tr>
              <tr>
                <td>OS Version</td><td>TengeOS 4.0.0.6 Global (Europe)</td>
              </tr>
              <tr>
                <td>Base Port</td><td>Xiaomi 17T Pro</td>
              </tr>
              <tr>
                <td>Android</td><td>17</td>
              </tr>
              <tr>
                <td>Build Type</td><td>Fenrir / Non-Fenrir</td>
              </tr>
              <tr>
                <td>Flashing Type</td><td>Hybrid (recovery/fastboot)</td>
              </tr>
            </table>
          </details>
          <details>
            <summary><code>Links</code></summary>
            <table bordered>
              <tr>
                <th colspan="2" align="center">Download</th>
              </tr>
              <tr>
                <td align="center"><a href="https://drive.google.com/file/d/1-SaywPsB9NHtwV-m757rivpVIklbJZ7N/view?usp=drive_link">Fenrir</a></td>
                <td align="center"><a href="https://drive.google.com/file/d/1rZLsZPsGGcnrFCI7PFdtpJ2-VQ51mGW0/view?usp=sharing">Non-Fenrir</a></td>
              </tr>
            </table>
            <ol>
              <li><a href="https://telegra.ph/How-to-flash-08-19">How to flash</a></li>
              <li><a href="https://telegra.ph/Changelog-09-25-4">Changelog</a></li>
              <li><a href="https://t.me/DuchampROM_screenshots/357">Screenshots</a></li>
              <li><a href="https://telegra.ph/Credits-08-30-11">Credits</a></li>
            </ol>
          </details>
          <details>
            <summary><code>Notes</code></summary>
            <ol>
              <li><u>CLEAN FLASH ONLY FOR FENRIR!</u></li>
              <li>For fullscreen aod <u>use 10 sec option</u></li>
              <li>To Reduce cpu clamping and cpusets, use <a href="https://t.me/DuchampROM_screenshots/343">this</a></li>
              <li>Already with ReSukiSU with SuSFS v2.3.0 (non-fenrir)</li>
            </ol>
          </details>
          <details>
            <summary><code>Bugs</code></summary>
            <ol>
              <li><u>Still have some bugs with fullscreen aod, so i recommended to NOT use it</u></li>
              <li>You tell me, this is beta hos</li>
            </ol>
          </details>
          EOF
          )

          jq -n \
            --arg chat_id "$TELEGRAM_CHAT_ID" \
            --arg html "$HTML" \
            '{
              chat_id: $chat_id,
              disable_web_page_preview: false,
              link_preview_options: {
                is_disabled: false
              },
              rich_message: {
                html: $html
              }
            }' > telegram_payload.json

          curl \
            --fail-with-body \
            --silent \
            --show-error \
            -X POST \
            "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendRichMessage" \
            -H "Content-Type: application/json" \
            --data @telegram_payload.json

